from src.deviation import Deviation

def test_deviation_init():
    assert Deviation(running_count = 0, true_count = 0) is not None

def test_norm():
    assert Deviation(running_count = 1, true_count = 4).norm(16,9) == 's'
    assert Deviation(running_count = 1, true_count = 3).norm(16,9) == 'h'
    assert Deviation(running_count = 1, true_count = 4).norm(16,10) == 's'
    assert Deviation(running_count = 0, true_count = 4).norm(16,10) == 'h'
    assert Deviation(true_count = 4).norm(15,10) == 's'
    assert Deviation(true_count = 3).norm(15,10) == 'h'
    assert Deviation(true_count = -1).norm(13,2) == 'd'
    assert Deviation(true_count = 2).norm(13,2) == 's'
    assert Deviation(true_count = 3).norm(12,2) == 's'
    assert Deviation(true_count = 2).norm(12,2) == 'h'
    assert Deviation(true_count = 2).norm(12,3) == 's'
    assert Deviation(true_count = 1).norm(12,3) == 'h'
    assert Deviation(running_count = -1).norm(12,4) == 'd'
    assert Deviation(running_count = 0).norm(12,4) == 's'
    assert Deviation(true_count = 4).norm(10,10) == 'd'
    assert Deviation(true_count = 3).norm(10,10) == 'h'
    assert Deviation(true_count = 3).norm(10,11) == 'd'
    assert Deviation(true_count = 2).norm(10,11) == 'h'
    assert Deviation(true_count = 1).norm(9,2) == 'd'
    assert Deviation(true_count = 0).norm(9,2) == 'h'
    assert Deviation(true_count = 3).norm(9,7) == 'd'
    assert Deviation(true_count = 2).norm(9,7) == 'h'
    assert Deviation(true_count = 2).norm(8,6) == 'd'
    assert Deviation(true_count = 1).norm(8,6) == 'h'
    assert Deviation().norm(2, 1) == 'h'

def test_ace():
    assert Deviation().ace(21,4) == 's'
    assert Deviation(true_count = 3).ace(19,4) == 'd'
    assert Deviation(true_count = 2).ace(19,4) == 's'
    assert Deviation(true_count = 1).ace(19,5) == 'd'
    assert Deviation(true_count = 0).ace(19,5) == 's'
    assert Deviation(running_count = -1).ace(19,6) == 's'
    assert Deviation(running_count = 1).ace(19,6) == 'd'
    assert Deviation(true_count = 1).ace(17,2) == 'd'
    assert Deviation(true_count = 0).ace(17,2) == 'h'
    assert Deviation().ace(20,4) == 's'

def test_split():
    assert Deviation(true_count = 6).split(20,4) == 'sp'
    assert Deviation(true_count = 5).split(20,4) == 's'
    assert Deviation(true_count = 5).split(20,5) == 'sp'
    assert Deviation(true_count = 4).split(20,5) == 's'
    assert Deviation(true_count = 4).split(20,6) == 'sp'
    assert Deviation(true_count = 3).split(20,6) == 's'
    assert Deviation().split(20,7) == 's'

def test_main():
    assert Deviation(running_count = 1, true_count = 4).main(16,9) == 's'
    assert Deviation(running_count = 1, true_count = 3).main(16,9) == 'h'
    assert Deviation(running_count = 1, true_count = 4).main(16,10) == 's'
    assert Deviation(running_count = 0, true_count = 4).main(16,10) == 'h'
    assert Deviation(true_count = 4).main(15,10) == 's'
    assert Deviation(true_count = 3).main(15,10) == 'h'
    assert Deviation(true_count = -1).main(13,2) == 'd'
    assert Deviation(true_count = 2).main(13,2) == 's'
    assert Deviation(true_count = 3).main(12,2) == 's'
    assert Deviation(true_count = 2).main(12,2) == 'h'
    assert Deviation(true_count = 2).main(12,3) == 's'
    assert Deviation(true_count = 1).main(12,3) == 'h'
    assert Deviation(running_count = -1).main(12,4) == 'd'
    assert Deviation(running_count = 0).main(12,4) == 's'
    assert Deviation(true_count = 4).main(10,10) == 'd'
    assert Deviation(true_count = 3).main(10,10) == 'h'
    assert Deviation(true_count = 3).main(10,11) == 'd'
    assert Deviation(true_count = 2).main(10,11) == 'h'
    assert Deviation(true_count = 1).main(9,2) == 'd'
    assert Deviation(true_count = 0).main(9,2) == 'h'
    assert Deviation(true_count = 3).main(9,7) == 'd'
    assert Deviation(true_count = 2).main(9,7) == 'h'
    assert Deviation(true_count = 2).main(8,6) == 'd'
    assert Deviation(true_count = 1).main(8,6) == 'h'
    assert Deviation(true_count = 3).main(19,4, ace = True) == 'd'
    assert Deviation(true_count = 2).main(19,4, ace = True) == 's'
    assert Deviation(true_count = 1).main(19,5, ace = True) == 'd'
    assert Deviation(true_count = 0).main(19,5, ace = True) == 's'
    assert Deviation(running_count = -1).main(19,6, ace = True) == 's'
    assert Deviation(running_count = 1).main(19,6, ace = True) == 'd'
    assert Deviation(true_count = 1).main(17,2, ace = True) == 'd'
    assert Deviation(true_count = 0).main(17,2, ace = True) == 'h'
    assert Deviation(true_count = 6).main(20,4, splittable = True) == 'sp'
    assert Deviation(true_count = 5).main(20,4, splittable = True) == 's'
    assert Deviation(true_count = 5).main(20,5, splittable = True) == 'sp'
    assert Deviation(true_count = 4).main(20,5, splittable = True) == 's'
    assert Deviation(true_count = 4).main(20,6, splittable = True) == 'sp'
    assert Deviation(true_count = 3).main(20,6, splittable = True) == 's'
    

